# Generated by Django 3.2.8 on 2021-11-01 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='beerreview',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='beerreview',
            name='bitterness',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=0),
        ),
        migrations.AlterField(
            model_name='beerreview',
            name='money_value',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=0),
        ),
    ]
