# Generated by Django 3.2.8 on 2021-11-07 18:43

from django.db import migrations
import slugger.fields


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='beerreview',
            name='slug',
            field=slugger.fields.AutoSlugField(default='style', populate_from='beer_style'),
        ),
    ]
