# Generated by Django 3.2.8 on 2021-11-17 21:06

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beer',
            name='beer_name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='beerreview',
            name='beer_image',
            field=cloudinary.models.CloudinaryField(blank=True, default='https://res.cloudinary.com/fernandascloud/image/upload/v1636886150/media/default-review-image.webp', max_length=255, verbose_name='image'),
        ),
    ]
