# Generated by Django 3.2.8 on 2021-11-17 21:22

from django.db import migrations
import slugger.fields


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20211117_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beerreview',
            name='slug',
            field=slugger.fields.AutoSlugField(default='style1', populate_from='<django.db.models.fields.related.ForeignKey>'),
        ),
    ]
