# Generated by Django 3.2.8 on 2021-10-17 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_alter_beerreview_beer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beerreview',
            name='beer_style',
            field=models.CharField(max_length=200),
        ),
    ]
