# Generated by Django 3.2.8 on 2021-11-07 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20211101_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beer',
            name='beer_name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='beerstyle',
            name='beer_style',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
