# Generated by Django 3.2.8 on 2021-10-18 22:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_alter_beerreview_beer_style'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beerreview',
            name='beer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.beer'),
        ),
        migrations.AlterField(
            model_name='beerreview',
            name='beer_style',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.beerstyle'),
        ),
    ]
