# Generated by Django 3.2.8 on 2021-11-17 21:42

from django.db import migrations
import slugger.fields


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_alter_beerreview_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beerreview',
            name='slug',
            field=slugger.fields.AutoSlugField(populate_from='beer_style'),
        ),
    ]
