# Generated by Django 3.2.8 on 2021-11-17 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_alter_beerreview_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beerreview',
            name='slug',
            field=models.CharField(max_length=50),
        ),
    ]
