# Generated by Django 3.2.8 on 2021-10-22 19:11

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_auto_20211018_2245'),
    ]

    operations = [
        migrations.AddField(
            model_name='beerreview',
            name='beer_image',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image'),
        ),
    ]
