# Generated by Django 3.2.8 on 2021-10-24 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_beerreview_beer_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beer',
            name='beer_name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='beerreview',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
