# Generated by Django 3.2.8 on 2021-10-25 11:25

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_auto_20211024_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beerreview',
            name='beer_image',
            field=cloudinary.models.CloudinaryField(default='static/images/beer_review_placeholder.jpg', max_length=255, verbose_name='image'),
        ),
    ]
